### PR TITLE
Add mutex lock to safe-guard bufio.Reader access in Executor

### PR DESCRIPTION
**Pull request by 0x161e-swei**
bufio is not thread/goroutine safe.   
Under high concurrency, the executor may read in multiple responses or empty response from the underlying process.

### CODE REVIEW

**Comment by 0x161e-swei** [comment]
Hi @mhenke1 @dgrove-oss , could you please take a look at this PR?

**Comment by dgrove-oss** [comment]
@michele-sciabarra -- can you please take a look at this PR?

**Comment by 0x161e-swei** [comment]
@msciabarra Thanks a lot for taking a look at this!

> Runtimes are not expected to execute concurrent requests.

My understanding from reading the openwhisk invoker implementation and container wrapper ([here](https://github.com/apache/openwhisk/blob/master/common/scala/src/main/scala/org/apache/openwhisk/core/containerpool/Container.scala#L161)) is that concurrent actionvations are possible for a single container (and therefore runtime).

> To implement concurrent requests a lot of work is required to create multiple executors of the functions and dispatch request to the free one.

Multiple executors could enable parallel execution of the actions if they talk to different action processes. However the concurrency is already handled by the goroutines that serve each of the HTTP requests.

This PR tries to make sure responses are parsed correctly when concurrent requests are sent to the go proxy while only one executor process executes the actions serially. 

Maybe a check of the concurrency config in the env variable is needed to make sure the mutex does not degrade the performance unnecessarily?

**Comment by msciabarra** [comment]
Yes it is true that the invoker supports concurrent requests but so far the only runtime that supports (experimentally afaik) the concurrent requests is the nodejs one. Actionloop based runtimes (python, php, go, ruby etc) does not. To implement parallel execution much more is needed. Actionloop proxy spawns an underlying process and communicate with it using a protocol request response. I know because I developed it. It receives a request write to the subprocess wait the result and return the result. To enable concurrency we should spawn multiple executors, and map each request/response in a concurrent way with a single executor. AFAIK your fix... fixes nothing but adds an unnecessary overhead. Did you experience an issue with it? Can you show the bug and let me replicate it?

**Comment by msciabarra** [comment]
> However the concurrency is already handled by the goroutines that >serve each of the HTTP requests.
No. The goroutine there is used only to avoid a blocking behaviour when the underlying processs does not answer becuause the function crashed or is taking too much time. There was not a goroutine before but some issues were detected. If the system would get concurrent requests everything will go out of sync: the first request would send a line to the underlying executor, then another line, and this is NOT what the actionloop protocol implementation does: it reads and write one line at a time. Long story short: it won't work with concurrency enabled. Proably some check are needed to refuse execution when enabling concurrency because actionloop currently does not support concurrency. We have been discussed if we really need it but multiple runtimes are not very different than multiple executors in a single docker image... Furthermore having multiple executor would consume more memory... I am not convinced it is worth implementing something so complex for a little gain.

**Review by sciabarracom — COMMENTED** [review]
This PR is meant so support concurrent execution but does not work - much more work is needed to enable concurrent execution - see my comments to the PR. As a result it adds an unnecessary overhead without any advantage.

**Comment by dgrove-oss** [comment]
Thanks for the detailed review @sciabarracom!

**Comment by bdoyle0182** [comment]
I thought adobe was using the concurrent executions feature in production so I don't know if it's still considered experimental? There's definitely value to it as it significantly reduces overhead with docker and cold starts for cpu light operations or functions that are memory heavy to start up requiring sizable memory provisioning but each execution is light on memory. I won't speak to go though as I'm not at all familiar with the language.

**Comment by 0x161e-swei** [comment]
> Did you experience an issue with it? Can you show the bug and let me replicate it?

I experienced a bug when I enable concurrent actions. I was using helm to deploy OW (https://github.com/apache/openwhisk-deploy-kube) with a yaml config:
```yaml
whisk:
  ...
  limits:
    actions:
      concurrency:
        max: 100
...
```
And I created action using   
`wsk -i action create hello hello.go --main hello --docker openwhisk/action-golang-v1.18:nightly --web true`
and inside `hello.go` I have 
``` go
package main
func Hello(obj map[string]interface{}) map[string]interface{} {
	msg := make(map[string]interface{})
	msg["body"] = "Hello World!"
	return msg
}
```
I am using [wrk2](https://github.com/giltene/wrk2) to drive the load:  
`wrk -t 1 -c 20 -R 500 -d 10s https://127.0.0.1:31001/api/v1/web/guest/default/hello.http`
The above command opens 20 connections and issues to total load of 500 requests per second.

[runHandler.go:90](https://github.com/apache/openwhisk-runtime-go/blob/master/openwhisk/runHandler.go#L90) gets executed from time to time as the response from line 72
`response, err := ap.theExecutor.Interact(body)` returns `{"body": "Hello World!"}\n{"body": "Hello World!"}\n`


>"However the concurrency is already handled by the goroutines that > serve each of the HTTP requests."
No. The goroutine there is used only to avoid a blocking behaviour when the underlying processs does not answer becuause the function crashed or is taking too much time.  

Sorry about the confusion, I was referring to the goroutines that are created in serving the HTTP requests in the net.http package [here](https://github.com/golang/go/blob/master/src/net/http/server.go#L3072). So there will be one goroutine running the `runHandler` function for each of the HTTP request the proxy receives.

This PR is not aiming to enable concurrent execution of the actions, but it tries to improve the safety of concurrent processing of the activataions. The actions are still serially executed by one executor process. Concurrent processing of the activations (e.g. parsing request header and body) improves performance as otherwise a second request can only be processed/parsed after the  first request completes.

I agree with the "out of sync" challenge:   
goroutine-1 for the http-req-1 could have written to the stdout of the "action process" first, and spawns up goroutine-3 waiting for response. And goroutine-2 for the http-req-2 writes the request body to the stdout of the action process and spawns up goroutine-4 waiting for response. It is possible goroutine-4 gets scheduled before goroutine-3 and actually reads back the response for http-req-1.   
So Perhaps a mutex wrapping the write line and read line operation in the `executor.Interact` could solve this?

Thanks again!

**Comment by msciabarra** [comment]
I am not sure of what the 'concurrent' does, I guess it enables concurrent execution but if it does I am not sure the solutions as simple as putting a lock around the interactions with the subprocess.

**Comment by style95** [comment]
@0x161e-swei 
BTW, why do you enable this configuration for the go runtime that does not support concurrency?

```
whisk:
  ...
  limits:
    actions:
      concurrency:
        max: 100
...
```

I am curious if such mixed results could happen without concurrency enabled as well.


@bdoyle0182 
We can't collect any logs if concurrency is enabled so I have considered it as an experimental feature for now.
Not sure how adobe handles logs.

**Comment by msciabarra** [comment]
I think if you use a hello action you will never see the problems you may have enabling concurrent execution. If it is works it is of pure luck because the actions is trivial and always returns the same answers without any delay. You should try something more meaningful, taking some time and so on. AFAIK you are lucky if an executor receiving concurrent actions does not get stuck. I am not sure if there are problems also in the initialization but AFAIK each runtime can be initialized only once! There is even a control that refues to re-initialize otherwise it can be a security hole.

**Comment by dgrove-oss** [comment]
> I thought adobe was using the concurrent executions feature in production so I don't know if it's still considered experimental? There's definitely value to it as it significantly reduces overhead with docker and cold starts for cpu light operations or functions that are memory heavy to start up requiring sizable memory provisioning but each execution is light on memory. I won't speak to go though as I'm not at all familiar with the language.

My understanding is that Adobe enables concurrent executions with a NodeJS based runtime (which doesn't use the go-based action proxy).

**Comment by 0x161e-swei** [comment]
> @0x161e-swei BTW, why do you enable this configuration for the go runtime that does not support concurrency?   

Hi @style95, there seems to be no way to enable concurrency for a specific runtime, the `action.limits.concurrency.maxConcurrent` configs are used inside ContinaerProxy and Invoker. I had it enabled sicne I was playing with nodejs runtime as well.


> I am curious if such mixed results could happen without concurrency enabled as well. 

According to [this line](https://github.com/apache/openwhisk/blob/master/core/invoker/src/main/scala/org/apache/openwhisk/core/containerpool/ContainerProxy.scala#L428):
Without the concurrency enabled (max set to 1), the ContainerProxy won't send another request until the first one completed and returned.

> I am not sure if there are problems also in the initialization but AFAIK each runtime can be initialized only once! 
Hi @msciabarra, with a single executor and runtime, we will not be initializing the runtime twice since the action proxy will only be writing to the stdin of the underlying action process.

**Comment by bdoyle0182** [comment]
That is correct if you turn on max concurrency as a system option, the system will attempt to send multiple requests to a runtime container regardless of what the runtime is. The feature is only available for nodejs right now. There's an open pr to add support for java. 

However the default is just 1 so if the user doesn't set it for an action then it's not used. Would be nice to have a safeguard, but as has been mentioned no one is really using the feature that we know of outside of adobe right now so there really hasn't been much coordinated investment into it so far.

**Comment by dgrove-oss** [comment]
Based on discussion, closing as not something that as currently mergable.

**Pull request closed without merging**
