### PR TITLE
Add golang 1.17

### PR DESCRIPTION
**Pull request by Luke-Roy-IBM**
Runtime is based on golang:1.17-buster

### CODE REVIEW

**Comment by dgrove-oss** [comment]
redundant with https://github.com/apache/openwhisk-runtime-go/pull/157?

**Comment by Luke-Roy-IBM** [comment]
@dgrove-oss Thanks for the info you are right

**Comment by dgrove-oss** [comment]
No worries.  Sorry that we were slow on merges in this repo. There's something messed up with my id and travis-ci on this repository.  It won't let me restart the test for #157, which is why it hasn't been merged.  If you want to re-open this PR, we could merge it instead of #157 if you need go 1.17 support quickly.

**Comment by Luke-Roy-IBM** [comment]
@dgrove-oss there is no rush just noticed we didn´t have 1.17 so thought would do it since you already have it we can wait for your pull request :)

**Pull request closed without merging**
