### PR TITLE
Pass system env to user's action

### PR DESCRIPTION
**Pull request by jiangpengcheng**

### CODE REVIEW

**Comment by style95** [comment]
It would be great if you leave some description and ramification of this change.

**Comment by rabbah** [comment]
> It would be great if you leave some description and ramification of this change.

+1. What's the reason for this change? Also this is different from other runtimes, I think. The environment is carefully constructed in the proxies.

**Comment by sciabarracom** [comment]
Also this can leave security holes.

**Comment by mrutkows** [comment]
Same concerns as expressed by Rodric and Michele... we should not expose general OS env. vars.  only specific variables are made available.  Chetan provided an answer on how to pass extra args to the runtime container as a reply to this question:
https://github.com/apache/openwhisk/issues/4308

I too am curious as to the problem/use case you are trying to solve/accomplish.

**Comment by jiangpengcheng** [comment]
sorry for the late response

our use case is that some of our users executed command(like `python3 --version`) in a python3 action, but they got a `python3 command not found` error, which looks strange for a python3 runtime environment, so I tried to pass some system env to runtime images

**Comment by jiangpengcheng** [comment]
I will close this as it does introduce some security holes

**Comment by mrutkows** [comment]
> sorry for the late response
> 
> our use case is that some of our users executed command(like `python3 --version`) in a python3 action, but they got a `python3 command not found` error, which looks strange for a python3 runtime environment, so I tried to pass some system env to runtime images

Actually, this is interesting... in that there may be a standard means to add runtime-specific env. vars (declared in some way by each runtime) that are acknowledged by the container factory.

**Pull request closed without merging**
