### PR TITLE
Add golang 1.19 Runtime

### PR DESCRIPTION
**Pull request by skywalkeretw**
Add latest runtime fo go (1.19)

### CODE REVIEW

**Comment by skywalkeretw** [comment]
@dgrove-oss Please review this Pull request :)

**Review by dgrove-oss — APPROVED** [review]
Looks good except for the one 1.18 => 1.19 change that was missed (see suggested fix)

**Comment by skywalkeretw** [comment]
@dgrove-oss fix has been added 👍

**Comment by skywalkeretw** [comment]
Would someone be so kind and merge the pull request thx :)

**Pull request merged**
